# Generated by Django 5.1.2 on 2024-10-23 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
