POST http://127.0.0.1:8000/auth/signup/
Content-Type: "application/json"

{ "username": "stan", "password": "rowhittz","email":"stan@sp.com" }

POST http://127.0.0.1:8000/auth/login/
Content-Type: "application/json"

{ "username": "stan", "password": "rowhittz" }